services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: njaeplume-next-client
    ports:
      - 3000:3000
    env_file:
      - .env.local
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
