import type { Config } from "tailwindcss";

import { nextui } from "@nextui-org/theme";

/** @type {import("tailwindcss").Config} */
const config = {
  content: [
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,md,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,md,jsx,tsx,mdx,css}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
        serif: ["var(--font-serif)", "serif"],
        display: ["var(--font-display)", "serif"],
        sansAlt: ["var(--font-sans-alt)", "sans-serif"],
      },
      fontWeight: {
        normal: "400",
        bold: "700",
      },
      typography: () => ({
        lightTheme: {
          css: {
            "--tw-prose-body": "#1D1B3C",
            "--tw-prose-headings": "#1D1B3C",
            "--tw-prose-lead": "#934DFF",
            "--tw-prose-links": "#934DFF",
            "--tw-prose-bold": "#1D1B3C",
            "--tw-prose-counters": "#A766FF",
            "--tw-prose-bullets": "#C799FF",
            "--tw-prose-hr": "#D4B3FF",
            "--tw-prose-quotes": "#1D1B3C",
            "--tw-prose-quote-borders": "#D4B3FF",
            "--tw-prose-captions": "#934DFF",
            "--tw-prose-code": "#1D1B3C",
            "--tw-prose-pre-code": "#F7F3FF",
            "--tw-prose-pre-bg": "#934DFF",
            "--tw-prose-th-borders": "#D4B3FF",
            "--tw-prose-td-borders": "#EEE5FF",
            "--tw-prose-invert-body": "#EDE9F6",
            "--tw-prose-invert-headings": "#EDE9F6",
            "--tw-prose-invert-lead": "#AB79F8",
            "--tw-prose-invert-links": "#AB79F8",
            "--tw-prose-invert-bold": "#EDE9F6",
            "--tw-prose-invert-counters": "#D19CFF",
            "--tw-prose-invert-bullets": "#E4AEFF",
            "--tw-prose-invert-hr": "#6D4AAA",
            "--tw-prose-invert-quotes": "#EDE9F6",
            "--tw-prose-invert-quote-borders": "#6D4AAA",
            "--tw-prose-invert-captions": "#AB79F8",
            "--tw-prose-invert-code": "#EDE9F6",
            "--tw-prose-invert-pre-code": "#2E1D4A",
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": "#6D4AAA",
            "--tw-prose-invert-td-borders": "#432C6A",
          },
        },
        darkTheme: {
          css: {
            "--tw-prose-body": "#EDE9F6",
            "--tw-prose-headings": "#EDE9F6",
            "--tw-prose-lead": "#AB79F8",
            "--tw-prose-links": "#AB79F8",
            "--tw-prose-bold": "#EDE9F6",
            "--tw-prose-counters": "#D19CFF",
            "--tw-prose-bullets": "#E4AEFF",
            "--tw-prose-hr": "#6D4AAA",
            "--tw-prose-quotes": "#EDE9F6",
            "--tw-prose-quote-borders": "#6D4AAA",
            "--tw-prose-captions": "#AB79F8",
            "--tw-prose-code": "#EDE9F6",
            "--tw-prose-pre-code": "#2E1D4A",
            "--tw-prose-pre-bg": "#AB79F8",
            "--tw-prose-th-borders": "#6D4AAA",
            "--tw-prose-td-borders": "#432C6A",
            "--tw-prose-invert-body": "#1D1B3C",
            "--tw-prose-invert-headings": "#1D1B3C",
            "--tw-prose-invert-lead": "#934DFF",
            "--tw-prose-invert-links": "#934DFF",
            "--tw-prose-invert-bold": "#1D1B3C",
            "--tw-prose-invert-counters": "#A766FF",
            "--tw-prose-invert-bullets": "#C799FF",
            "--tw-prose-invert-hr": "#D4B3FF",
            "--tw-prose-invert-quotes": "#1D1B3C",
            "--tw-prose-invert-quote-borders": "#D4B3FF",
            "--tw-prose-invert-captions": "#934DFF",
            "--tw-prose-invert-code": "#1D1B3C",
            "--tw-prose-invert-pre-code": "#F7F3FF",
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": "#D4B3FF",
            "--tw-prose-invert-td-borders": "#EEE5FF",
          },
        },
      }),
    },
  },
  variants: {
    extend: {
      fontStyle: ["responsive", "hover", "focus", "active"],
      fontWeight: ["responsive", "hover", "focus", "active"],
    },
  },
  darkMode: "class",
  safelist: [
    {
      pattern:
        /bg-(primary|secondary|success|warning|danger)-[5|1|2|3|4|6|7|8|9]00/,
      variants: ["hover", "focus", "active"],
    },
  ],
  plugins: [
    require("@tailwindcss/typography"),
    nextui({
      themes: {
        light: {
          colors: {
            background: "#F8F5EE",
            foreground: "#C49288",
            primary: {
              // 50: "#F7F3FF",
              // 100: "#EEE5FF",
              // 200: "#E1CCFF",
              // 300: "#D4B3FF",
              // 400: "#C799FF",
              // 500: "#BB80FF",
              // 600: "#A766FF",
              // 700: "#934DFF",
              // 800: "#7F33FF",
              // 900: "#6B1AFF",
              foreground: "#C49288",
              DEFAULT: "#C799FF",
            },
            secondary: {
              // 50: "#F3F1FF",
              // 100: "#E8E5FF",
              // 200: "#D1CCFF",
              // 300: "#BAB3FF",
              // 400: "#A499FF",
              // 500: "#8E80FF",
              // 600: "#7866FF",
              // 700: "#6252FF",
              // 800: "#4B3EFF",
              // 900: "#3529FF",
              foreground: "#C49288",
              DEFAULT: "#A499FF",
            },
            success: {
              // 50: "#F2FFF7",
              // 100: "#E4FFEE",
              // 200: "#C9FFD7",
              // 300: "#ADFFBF",
              // 400: "#92FFA7",
              // 500: "#76FF8F",
              // 600: "#5AFF77",
              // 700: "#3EFF5F",
              // 800: "#22FF47",
              // 900: "#07FF2F",
              foreground: "#C49288",
              DEFAULT: "#92FFA7",
            },
            warning: {
              // 50: "#FFF9E8",
              // 100: "#FFF2D1",
              // 200: "#FFE5A3",
              // 300: "#FFD976",
              // 400: "#FFCC48",
              // 500: "#FFBF1A",
              // 600: "#FFB200",
              // 700: "#FFA500",
              // 800: "#FF9800",
              // 900: "#FF8B00",
              foreground: "#C49288",
              DEFAULT: "#FFCC48",
            },
            danger: {
              // 50: "#FFE8EB",
              // 100: "#FFD1D7",
              // 200: "#FFA3AF",
              // 300: "#FF7687",
              // 400: "#FF495F",
              // 500: "#FF1A37",
              // 600: "#FF0020",
              // 700: "#E6001C",
              // 800: "#CC0018",
              // 900: "#B30014",
              foreground: "#C49288",
              DEFAULT: "#FF495F",
            },
          },
        },
        dark: {
          colors: {
            background: "rgb(41 37 36)", // "#2A1D16",
            foreground: "#DAB6A5",
            primary: {
              // 50: "#2E1D4A",
              // 100: "#432C6A",
              // 200: "#583B8A",
              // 300: "#6D4AAA",
              // 400: "#825ACB",
              // 500: "#9769EB",
              // 600: "#AB79F8",
              // 700: "#BE8BFF",
              // 800: "#D19CFF",
              // 900: "#E4AEFF",
              foreground: "#DAB6A5",
              DEFAULT: "#825ACB",
            },
            secondary: {
              // 50: "#1C1B36",
              // 100: "#2A294E",
              // 200: "#383767",
              // 300: "#464580",
              // 400: "#55539A",
              // 500: "#6362B3",
              // 600: "#7271CC",
              // 700: "#8180E6",
              // 800: "#908FFF",
              // 900: "#9E9DFF",
              foreground: "#DAB6A5",
              DEFAULT: "#55539A",
            },
            success: {
              // 50: "#1D2B1F",
              // 100: "#294236",
              // 200: "#35594D",
              // 300: "#417064",
              // 400: "#4D877B",
              // 500: "#599E92",
              // 600: "#65B5A9",
              // 700: "#71CCBF",
              // 800: "#7DE3D6",
              // 900: "#89FAED",
              foreground: "#DAB6A5",
              DEFAULT: "#4D877B",
            },
            warning: {
              // 50: "#33281C",
              // 100: "#4C3E29",
              // 200: "#655536",
              // 300: "#7E6C43",
              // 400: "#978350",
              // 500: "#B09A5D",
              // 600: "#C9B16A",
              // 700: "#E2C877",
              // 800: "#FBEF84",
              // 900: "#FFFCA1",
              foreground: "#DAB6A5",
              DEFAULT: "#978350",
            },
            danger: {
              // 50: "#3C1C21",
              // 100: "#592931",
              // 200: "#763741",
              // 300: "#934551",
              // 400: "#B15361",
              // 500: "#CE6171",
              // 600: "#EB6F81",
              // 700: "#FF7F91",
              // 800: "#FF8FA1",
              // 900: "#FFA1B3",
              foreground: "#DAB6A5",
              DEFAULT: "#B15361",
            },
          },
        },
      },
    }),
  ],
} satisfies Config;

export default config;
